version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "bundler"
    directory: "apis"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
