# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require 'simplecov'
SimpleCov.start do
  add_filter 'test/influxdb'
end

if ENV['CI'] == 'true'
  require 'simplecov-cobertura'
  SimpleCov.formatter = SimpleCov::Formatter::CoberturaFormatter

  # Monkeypatch REXML to handle malformed XML from simplecov-cobertura 1.4.2/2.1.0
  # see: https://github.com/dashingrocket/simplecov-cobertura/issues/31
  require 'rexml/document'
  module REXML
    class Document
      alias_method :original_initialize, :initialize
      def initialize(source = nil, context = {})
        if source.is_a?(String) && source.include?('Generated by simplecov-cobertura') && !source.include?('<coverage')
          source_with_root = source + "\n<coverage/>"
          original_initialize(source_with_root, context)
          # Remove the dummy root element so simplecov-cobertura can add its own
          delete_element('/coverage')
        else
          original_initialize(source, context)
        end
      end
    end
  end
end

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'influxdb-client-apis'
require 'influxdb-client'

require 'minitest/autorun'
require 'minitest/ci'

require 'webmock/minitest'
